### ISSUE TITLE
DATA statements on the same line # get messed up

### ISSUE THREAD

**Issue by dbrucemoore** [nowhereman999/BASIC-To-6809#5]
If a DATA statement has its one line number, proper result. 
If there are several DATA statements separated by ":", subsequent  data read incorrectly.
[SPACELAB2B.asm.txt](https://github.com/user-attachments/files/16551552/SPACELAB2B.asm.txt)
[SPACELAB2b.TXT](https://github.com/user-attachments/files/16551553/SPACELAB2b.TXT)
<img width="548" alt="Screenshot 2024-08-08 at 12 32 51 PM" src="https://github.com/user-attachments/assets/4398146e-ad41-403f-9071-420bd45c2240">

**Comment by nowhereman999** [comment]
Rewrote a lot of code to handle DATA statements.  It can now handle this properly in Version 2.0 which will be uploaded soon

**Comment by dbrucemoore** [comment]
I revisited this and it runs, gives an "OK" prompt, but no cursor to enter commands.  (in VCC) . then after about 20 seconds garbage appears on the screen.

So it isn't returning to basic properly? (v4.32(
